

INSERT INTO autores (id, pseudonimo_id, pseudonimo, cidade_id, alcunha, nome, datanasc, realnasc, datamorte, realmorte, biografia, created_at, updated_at) VALUES
(216, NULL, NULL, NULL, 'João Cabral de Melo Neto', 'João Cabral de Melo Neto', NULL, NULL, NULL, NULL, NULL, now(), now()),
(244, NULL, 'Cicla', NULL, 'Juba', 'Ciclano de Tal', NULL, NULL, NULL, NULL, NULL, now(), now()),
(245, NULL, 'Inenarrável', NULL, 'Gubi', 'Marco Gubitoso', NULL, NULL, NULL, NULL, NULL, now(), now()),
(246, NULL, NULL, NULL, 'Aldo Bizzocchi', 'Aldo', NULL, NULL, NULL, NULL, NULL, now(), now()),
(247, NULL, NULL, NULL, 'Olavo Bilac', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(248, NULL, NULL, NULL, 'Augusto dos Anjos', 'Augusto Silva dos Anjos', NULL, NULL, NULL, NULL, NULL, now(), now()),
(252, NULL, 'Rick Ross', NULL, 'Rick Ross', 'Ricky Z. Ross', NULL, NULL, NULL, NULL, NULL, now(), now()),
(253, NULL, NULL, NULL, 'Nicki Minaj', 'Nicki L Minaj', NULL, NULL, NULL, NULL, NULL, now(), now()),
(255, NULL, '', NULL, 'Anônimo', '', NULL, NULL, NULL, NULL, '', now(), now()),
(256, NULL, 'Álvaro de Campos', NULL, 'Fernando Pessoa', 'Fernando P. Pessoa', NULL, NULL, NULL, NULL, '', now(), now()),
(257, NULL, NULL, NULL, 'Björk', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(258, NULL, NULL, NULL, 'Sylvia Colombo', 'Sylvia Colombo', NULL, NULL, NULL, NULL, 'Jornalista da Folha de S. Paulo', now(), now()),
(270, NULL, 'Contardão', NULL, 'Contardo Calligaris', 'Contardo G. Calligaris', '1900-12-31', '1900-12-31', '2000-12-31', '2000-12-31', 'Cara legal', now(), now()),
(271, NULL, NULL, NULL, 'Janes Eyre', 'Janes T. Eyre', '1850-12-31', '1850-12-31', '1938-12-31', '1938-12-31', NULL, now(), now()),
(274, NULL, NULL, NULL, 'Yuri Roberto ', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(282, NULL, 'Mario', NULL, 'Mário Eduardo Viaro', 'Mário Eduardo Viaro', '1934-10-02', '1900-02-10', '1964-10-02', '1960-02-10', 'Soy yo', now(), now()),
(283, NULL, 'Outro', NULL, 'Outro Mário Eduardo Viaro', 'Outro', '1978-12-31', '1978-12-31', NULL, NULL, 'Kekeké', now(), now()),
(284, NULL, 'Lerdo', NULL, 'Manuel Lordoso', 'Manuel Lordoso', '1999-12-31', '1999-12-31', '2000-12-31', '2000-12-31', NULL, now(), now()),
(285, NULL, NULL, NULL, 'Clayton', 'Claytus Romanus', '1999-12-31', '1999-12-31', NULL, NULL, NULL, now(), now()),
(286, NULL, NULL, NULL, 'Mário Eduardo Viaro II', 'Marius Viarus', '1968-12-31', '1968-12-31', NULL, NULL, NULL, now(), now()),
(289, NULL, 'Taturana', NULL, 'Marcus Plinius', 'Marcus Plinius Damascenus', '1999-12-31', '1999-12-31', '2001-12-31', '2001-12-31', 'Cabra estranho', now(), now()),
(290, NULL, 'Babuíno', NULL, 'Otavianus Augustus Celeberrimus', 'Otavianus Augustissimus Nonceleber', '1999-12-31', '1999-12-31', '1998-12-31', '1998-12-31', 'Morreu antes de nascer', now(), now()),
(291, NULL, 'Matutissimus', NULL, 'Matutissimus Zorobabel', 'Zorobabel', '2009-12-31', '2009-12-31', NULL, NULL, 'Coisas estranhas podem ser inseridas aqui impunemente', now(), now()),
(292, NULL, 'Lady Gaga', NULL, 'Aarão José', 'Tutancamon da Silva', '8989-12-31', '8989-12-31', '9999-12-31', '9999-12-31', 'Hamalapepalezibalahamalapepalezibalepo', now(), now()),
(293, NULL, 'Cérebro', NULL, 'Tantã', 'Tantanivaldo Soares', '1789-12-31', '1789-12-31', '1777-12-31', '1777-12-31', 'Eu nasci há dez mil anos atrás', now(), now()),
(294, NULL, 'AJS', NULL, 'Aarão Joaquim', 'Aarão Joaquim da Silva', '1995-12-31', '1995-12-31', '1999-12-31', '1999-12-31', 'Eu sei lá', now(), now()),
(295, NULL, 'BSS', NULL, 'Baal de Sousa', 'Baal de Sousa da Silva', '1995-12-31', '1995-12-31', '1999-12-31', '1999-12-31', 'Biografia', now(), now()),
(296, NULL, 'CMS', NULL, 'Cláudio Manuel', 'Cláudio Manuel da Silva', '1995-12-31', '1995-12-31', '1999-12-31', '1999-12-31', 'Aifargoib', now(), now()),
(297, NULL, 'DRS', NULL, 'Daniel Rodrigues', 'Daniel Rodrigues da Silva', '1995-12-31', '1995-12-31', '1999-12-31', '1999-12-31', 'Quare irritas me?', now(), now()),
(298, NULL, 'ETS', NULL, 'Eusébio Tavares', 'Eusébio Tavares da Silva', '1995-12-31', '1995-12-31', '1999-12-31', '1999-12-31', 'MAMAMAMAMAMAMAMAMAMAMA', now(), now()),
(299, NULL, 'FJS', NULL, 'Filisteu José', 'Filisteu José da Silva', '1995-12-31', '1995-12-31', '1999-12-31', '1999-12-31', 'TARATATÁ!!!!!!', now(), now()),
(309, NULL, 'Alberto Caeiro', NULL, 'Fernando Pessoa', 'Fernando Pessoa', '1900-12-31', '1900-12-31', '1908-12-31', '0', NULL, now(), now()),
(310, NULL, 'Ricardo Reis', NULL, 'Fernando Pessoa', 'Fernando Pessoa', '1889-12-31', '1889-12-31', '1900-12-31', '0', NULL, now(), now()),
(313, NULL, NULL, NULL, 'josé da Silva', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(314, NULL, NULL, NULL, 'Olavo Bilac da Silva', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(316, NULL, NULL, NULL, 'Tatu Bola', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(317, NULL, NULL, NULL, 'Tomates Verdes', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(318, NULL, NULL, NULL, 'Tatu Bola', NULL, '1235-12-31', '1235-12-31', NULL, NULL, NULL, now(), now()),
(319, NULL, NULL, NULL, 'Tatu Bola', NULL, '1334-12-31', '1334-12-31', '1356-12-31', '1356-12-31', NULL, now(), now()),
(320, NULL, NULL, NULL, 'Tatu Bola', 'Noel Rosa', NULL, NULL, '1934-12-12', '1934-12-12', NULL, now(), now()),
(323, NULL, 'Hulk', NULL, 'Mário Eduardo Viaro', 'Mário Eduardo Viaro', '1968-05-01', '1968-05-01', NULL, '31-04-1968', 'Phoenix renatura.', now(), now()),
(324, NULL, 'O Viking', NULL, 'Olavo Hófursson', 'Olaf Smagduntur Hófursson', '1990-05-01', '1990-05-01', '1990-06-01', '1990-06-01', 'Brevis vita', now(), now()),
(326, NULL, NULL, NULL, 'Cecil Bernardo de Mil', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(327, NULL, NULL, NULL, 'Cecil B. de Mil', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(328, NULL, 'EE', NULL, 'Manuel Bernardes de Sousa', 'Emanuel Ebernardes', '2010-09-09', '09/09/2010', '2010-09-10', '10/09/2010', 'Um cara legal', now(), now()),
(329, NULL, 'Marião', NULL, 'Mário Eduardo Viaro', 'Mário Eduardo Viaro da Silva', '1968-05-01', '1968-05-01', '2068-05-01', '2068-05-01', 'Cem anos de NEHiLP', now(), now()),
(330, NULL, 'Turquinho', NULL, 'Mustafa Abdullah', 'Ibrahim Muhammad Al-Qummi', '1900-08-01', '1900-08-01', '1945-09-01', '1945-09-01', 'Albahad Mussaf el-Burajiru', now(), now()),
(331, NULL, 'Xaveco', NULL, 'José  Xavier', 'José Almeida Xavier', '1912-12-12', '12/12/1912', '2114-09-15', '15/09/2114', 'viveu pacas', now(), now()),
(332, NULL, NULL, NULL, 'José Almeida Xavier', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(333, NULL, NULL, NULL, 'Manuel Bernardes de Sousa', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(334, NULL, 'Mário José Viaro', NULL, 'Mário Eduardo Viaro', 'Mário Ricardo Viaro', '1968-05-01', '1968-05-01', '2068-05-01', '2068-05-01', 'Centenário', now(), now()),
(336, NULL, 'Caramboles', NULL, 'José Carango', 'José Carangoles', '1968-05-01', '1968-05-01', '2000-06-02', '02/06/2000', NULL, now(), now()),
(337, NULL, '', NULL, 'Mário de Andrade', 'Mário Raul de Moraes Andrade', NULL, '09/10/1893', NULL, '25/02/1945', '', now(), now()),
(339, NULL, NULL, NULL, 'Augusto dos Anjos', 'Augusto de Carvalho Rodrigues dos Anjos', '1884-04-20', '20/04/1884', '1914-11-12', '12/11/1914', NULL, now(), now()),
(340, NULL, NULL, NULL, 'Augusto dos Anjos', 'Augusto de Carvalho Rodrigues dos Anjos', '1884-04-20', '20/04/1884', '1914-11-12', '12/11/1914', NULL, now(), now()),
(341, NULL, NULL, NULL, 'Autorteste', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(343, NULL, NULL, NULL, 'Autorteste2', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(344, NULL, NULL, NULL, 'Autorteste3', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(345, NULL, NULL, NULL, 'Autorteste4', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(346, NULL, NULL, NULL, 'Autorteste5', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(347, NULL, NULL, NULL, 'Autorteste6', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(348, NULL, NULL, NULL, 'Autorteste7', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(349, NULL, NULL, NULL, 'teste10', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(350, NULL, NULL, NULL, 'Augusto dos Anjos', 'Augusto de Carvalho Rodrigues dos Anjos', '1884-04-20', '20/4/1884', '1914-11-12', '12/11/1914', NULL, now(), now()),
(351, NULL, NULL, NULL, 'Mário de Andrade', 'Mário Raul de Moraes de Andrade', '1893-10-09', '09/10/1893', '1945-02-25', '25/02/1945', NULL, now(), now()),
(353, NULL, '', NULL, 'Jerônimo Cardoso', 'Jerônimo Cardoso', NULL, 'c1510', NULL, '1569', '"mestre degramática em Lisboa a partir do primeiro terço doséc. XVI. Nascido em Lamego (c. 1508, now(), now()), estegramático colhe formação na universidade deSalamanca. Daí regressa em 1530 e logo deve terpassado a ensinar em Lisboa, próximo daUniversidade; os bons resultados conseguidosdevem ter-lhe assegurado reputação, pois logo em1536 é cooptado para proferir a oratio sapientiaeno início do ano escolar na Universidade. Teráplaneado deslocar-se a Paris, para aí frequentar auniversidade, esperançado possivelmente emusufruir de alguma bolsa de estudo que o rei D.João III concedia por esses tempos, mas não pareceque o tenha feito."(Aires A. Nascimento)http://ww3.fl.ul.pt/biblioteca/biblioteca_digital/docs/res93.pdf', now(), now()),
(354, NULL, '', NULL, 'Mário de Andrade', 'Mário Raul de Moraes Andrade', NULL, '09/10/1893', NULL, '25/02/1945', '', now(), now()),
(355, NULL, '', NULL, 'Osmar Freitas Jr', '', NULL, NULL, NULL, NULL, '', now(), now()),
(356, NULL, '', NULL, 'Olavo Bilac', 'Olavo Brás Martins dos Guimarães Bilac', '1865-12-16', '16/12/1865', '1918-12-28', '28/12/1918', '', now(), now()),
(357, NULL, NULL, NULL, 'Hermínio C. Miranda', 'Hermínio Corrêa de Miranda', '1920-01-05', '5/1/1920', '2013-07-08', '8/7/2013', NULL, now(), now()),
(358, NULL, NULL, NULL, 'Hermínio C. Miranda', 'Hermínio Corrêa de Miranda', '1920-01-05', '5/1/1920', '2013-07-08', '8/7/2013', NULL, now(), now()),
(359, NULL, '', NULL, 'Teotônio José Juzarte', '', NULL, NULL, NULL, NULL, '', now(), now()),
(360, NULL, NULL, NULL, 'Jonas Soares de Souza', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(361, NULL, NULL, NULL, 'Miyoko Makino', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(362, NULL, NULL, NULL, 'Teotônio José Juzarte', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(363, NULL, NULL, NULL, 'Jonas Soares de', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(364, NULL, NULL, NULL, 'Jonas Soares de Souza', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(365, NULL, NULL, NULL, 'Miyoko Makino', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(366, NULL, NULL, NULL, 'Jonas Soares de Souza', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(367, NULL, NULL, NULL, 'Teotônio José Juzarte', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(368, NULL, NULL, NULL, 'Jonas Soares de Souza', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(369, NULL, NULL, NULL, 'Miyoko Makino', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(370, NULL, NULL, NULL, 'Teotônio José Juzarte', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(371, NULL, NULL, NULL, 'Jonas Soares de Souza', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(372, NULL, NULL, NULL, 'Miyoko Makino', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(373, NULL, '', NULL, 'Teotônio José Juzarte', '', NULL, NULL, NULL, NULL, '', now(), now()),
(374, NULL, NULL, NULL, 'Jonas Soares de Souza', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(375, NULL, NULL, NULL, 'Miyoko Makino', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(376, NULL, '', NULL, 'Menotti del Picchia', 'Paulo Menotti del Picchia', NULL, '20/03/1892', NULL, '23/08/1988', '', now(), now()),
(377, NULL, '', NULL, 'Gilse Campos', '', NULL, NULL, NULL, NULL, '', now(), now()),
(382, NULL, '', NULL, 'Teotônio José Juzarte', '', NULL, NULL, NULL, NULL, '', now(), now()),
(383, NULL, 'DOnnn', NULL, 'Don Quixote', 'Don', NULL, NULL, NULL, NULL, NULL, now(), now()),
(384, NULL, NULL, NULL, 'Duarte Nunes de Leão', NULL, NULL, '1530', NULL, '1608', 'Conhecido por Duarte Nunez OU Nunes do Liam OU Lião.', now(), now()),
(385, NULL, NULL, NULL, 'António Gonçalves', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(386, NULL, NULL, NULL, 'Diogo Fernandez', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(387, NULL, NULL, NULL, 'Balthasar da Costa', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(388, NULL, NULL, NULL, 'Gaspar de Seixas', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(389, NULL, NULL, NULL, 'Jorge da Costa', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(390, NULL, NULL, NULL, 'LEÃO, Duarte Nunes de, fl. 1530-1608. ', 'Duarte Nunes de Leão', NULL, NULL, NULL, NULL, 'É considerado o autor intelectual da obra completa nas referências bibliográficas da Biblioteca Nacional de Portugal (BNP, now(), now()), mas é também organizador, visto que as leis foram "collegidas e relatadas pelo licenciado". Conhecido por Duarte Nunez OU Nunes do Liam OU Lião.', now(), now()),
(391, NULL, NULL, NULL, 'GONÇALVES, António, fl. 1566-1576.', 'António Gonçalves', NULL, NULL, NULL, NULL, 'Sediado em Lisboa. É o impressor da obra, dado como autor nas referências bibliográficas da BNP.', now(), now()),
(392, NULL, NULL, NULL, 'LEÃO, Duarte Nunes de, fl. 1530-1608. ', 'Duarte Nunes de Leão', NULL, NULL, NULL, NULL, 'É considerado o autor intelectual da obra completa nas referências bibliográficas da Biblioteca Nacional de Portugal (BNP, now(), now()), mas é também organizador, visto que as leis foram "collegidas e relatadas pelo licenciado". Conhecido por Duarte Nunez OU Nunes do Liam OU Lião.', now(), now()),
(393, NULL, NULL, NULL, 'GONÇALVES, António, fl. 1566-1576. ', 'António Gonçalves', NULL, NULL, NULL, NULL, 'É o impressor da obra, dado como autor nas referências bibliográficas da BNP.', now(), now()),
(394, NULL, NULL, NULL, 'Luiz da Silva Pereira Oliveira', 'Luiz da Silva Pereira Oliveira', NULL, NULL, NULL, NULL, 'Cavalleiro professo na Ordem de Christo, corregedor da Comarca de Miranda do Douro, natural de Fontellas, e socio da Real Academia das Sciencias de Lisboa.', now(), now()),
(395, NULL, NULL, NULL, 'Pedro Antonio de Oliveira', 'Pedro Antonio de Oliveira', NULL, NULL, NULL, NULL, 'redactor e cirurgiao', now(), now()),
(396, NULL, NULL, NULL, 'Antonio Carvalho da Costa', 'P. Antonio Carvalho da Costa', NULL, NULL, NULL, NULL, 'Segundo o frontispício da obra:"Clerigo do Habito de S.Pedro, Mathematico, Natural de Lisboa"', now(), now()),
(397, NULL, NULL, NULL, 'Valentim da Costa Deslandes', NULL, NULL, NULL, NULL, NULL, 'Segundo o frontispício da obra:"Impressor de Sua Magestade, ', now(), now()),
(398, NULL, '', NULL, 'José Soares da Silva', '', NULL, NULL, NULL, NULL, '', now(), now()),
(399, NULL, NULL, NULL, 'Padre Balthezar Tellez', 'Balthezar Tellez', NULL, NULL, NULL, NULL, '"Natural de Lisboa, Provincial da Prov', now(), now()),
(400, NULL, NULL, NULL, 'Padre Manoel D Almeyda', 'Manoel D Almeyda', NULL, NULL, NULL, NULL, '"Natural de Vizeu, Provincial e Visitador na India"', now(), now()),
(401, NULL, NULL, NULL, 'Dom Francisco Manoel de Mello', 'Francisco Manoel de Mello', NULL, NULL, NULL, NULL, 'autor da nota biogr', now(), now()),
(402, NULL, NULL, NULL, 'Manoel Dias', 'Manoel Dias', NULL, NULL, NULL, NULL, '"impressor da Universidade" (de Coimbra)', now(), now()),
(403, NULL, '', NULL, 'Ambrósio Pires', '', NULL, NULL, NULL, NULL, '', now(), now()),
(404, NULL, '', NULL, 'José Eugênio', '', NULL, NULL, NULL, NULL, '', now(), now()),
(405, NULL, '', NULL, 'Marcos Sergio Silva', '', NULL, NULL, NULL, NULL, '', now(), now()),
(406, NULL, NULL, NULL, 'Alberto Helena Jr.', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(407, NULL, NULL, NULL, 'Aimoré Moreira', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(408, NULL, NULL, NULL, 'José Augusto Ferreira', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(409, NULL, NULL, NULL, 'Joaquim Augusto da Silva', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(410, NULL, NULL, NULL, 'W. Alves', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(411, NULL, '', NULL, 'Domício da Gama', '', NULL, NULL, NULL, NULL, '', now(), now()),
(412, NULL, NULL, NULL, 'Fausto Neto', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(413, NULL, NULL, NULL, 'Divino Fonseca', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(414, NULL, NULL, NULL, 'Correia Lima', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(415, NULL, NULL, NULL, 'Jáder de Oliveira', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(416, NULL, NULL, NULL, 'Hedyl Valle Júnior ', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(417, NULL, NULL, NULL, 'João Carlos Rodriguez', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(418, NULL, NULL, NULL, 'Lenivaldo Aragão', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(419, NULL, NULL, NULL, 'Roberto José da Silva', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(420, NULL, '', NULL, 'Zinho Siqueira', '', NULL, NULL, NULL, NULL, '', now(), now()),
(421, NULL, NULL, NULL, 'Marcelo Vaz', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(422, NULL, NULL, NULL, 'Milton Costa Carvalho', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(423, NULL, NULL, NULL, 'Alceste Pinheiro', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(424, NULL, NULL, NULL, 'Maria', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(425, NULL, NULL, NULL, 'Joaquim Mattoso', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(426, NULL, NULL, NULL, 'Analu Braggio', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(427, NULL, NULL, NULL, 'Michel Laurence ', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(428, NULL, NULL, NULL, 'Teixeira Heizer', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(429, NULL, NULL, NULL, 'Marcelo Pontes', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(430, NULL, NULL, NULL, 'Aristélio Andrade', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(431, NULL, NULL, NULL, 'Patrício Renato', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(432, NULL, NULL, NULL, 'Plínio Marcos', 'Plínio Marcos de Barros', NULL, '29/09/1935', NULL, '19/09/1999', 'https://pt.wikipedia.org/wiki/Plínio_Marcos', now(), now()),
(433, NULL, NULL, NULL, 'A. Lopes de Moraes', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(434, NULL, NULL, NULL, 'Paulo Barros', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(435, NULL, NULL, NULL, 'C. F. Guedes Alcôforado ', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(436, NULL, NULL, NULL, 'Diégues Junior', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(437, NULL, NULL, NULL, 'J. Tertuliano', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(438, NULL, NULL, NULL, 'F. Domingues', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(439, NULL, NULL, NULL, 'Antonio Pindahyba', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(440, NULL, NULL, NULL, 'Francisco Goulart', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(441, NULL, NULL, NULL, 'Ezequiel Santos Junior', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(442, NULL, NULL, NULL, 'John Grierson', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(443, NULL, NULL, NULL, 'Cyro Siqueira', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(444, NULL, '', NULL, 'José Carlos Avellar', '', NULL, NULL, NULL, NULL, '', now(), now()),
(445, NULL, '', NULL, 'Pagú', 'Patrícia Rehder Galvão', NULL, '09/06/1910', NULL, '12/12/1962', 'https://pt.wikipedia.org/wiki/Pagu', now(), now()),
(446, NULL, NULL, NULL, 'João de Andrade Corvo', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(447, NULL, NULL, NULL, 'Jean Louis Ferrier', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(448, NULL, '', NULL, 'Jules Mary', '', NULL, NULL, NULL, NULL, '', now(), now()),
(449, NULL, '', NULL, 'Cobra', 'Patrícia Rehder Galvão', NULL, '09/06/1910', NULL, '12/12/1962', '', now(), now()),
(450, NULL, '', NULL, 'Alvimar', '', NULL, NULL, NULL, NULL, '', now(), now()),
(451, NULL, NULL, NULL, 'Américo Brasileiro', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(452, NULL, NULL, NULL, ' Eduardo Maciel Wanderley ', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(453, NULL, NULL, NULL, 'Julia de Carvalho', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(454, NULL, NULL, NULL, 'L. França', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(455, NULL, NULL, NULL, 'Silverio Lins', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(456, NULL, NULL, NULL, 'Arthur Ferreira', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(457, NULL, '', NULL, 'Nelson Rodrigues', 'Nelson Falcão Rodrigues', NULL, '23/08/1912', NULL, '21/12/1980', 'https://pt.wikipedia.org/wiki/Nelson_Rodrigues', now(), now()),
(458, NULL, NULL, NULL, 'Aluizio Alves Filho', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(459, NULL, NULL, NULL, 'Marco Aurélio Guimarães', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(460, NULL, NULL, NULL, 'Fritz Teixeira de Salles', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(461, NULL, '', NULL, 'Roberto Adolpho', '', NULL, NULL, NULL, NULL, '', now(), now()),
(462, NULL, NULL, NULL, 'Barrêto Rocha', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(463, NULL, NULL, NULL, 'U.T.', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(464, NULL, NULL, NULL, 'Erwin Theodor', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(465, NULL, NULL, NULL, 'Girardin', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(466, NULL, 'W.', NULL, 'W.', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(467, NULL, NULL, NULL, 'José Augusto Barrêto de Mello Rocha', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(468, NULL, NULL, NULL, 'Antonio Corrêa de Lacerda', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(469, NULL, NULL, NULL, 'João Pereira da Cunha e Queiros', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(470, NULL, NULL, NULL, 'Joaquim Pedro de Morais Bitancourt', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(471, NULL, NULL, NULL, 'Joze Joaquim da Silva', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(472, NULL, NULL, NULL, 'Balthazar Alves Pastana', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(473, NULL, NULL, NULL, 'Joze Rodrigues Lima', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(474, NULL, NULL, NULL, 'Manoel Gomes Pinto', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(475, NULL, 'J. J. S.', NULL, 'J. J. S.', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(476, NULL, NULL, NULL, 'Lemyr Martins', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(477, NULL, NULL, NULL, 'Adalberto Menezes de Oliveira', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(478, NULL, NULL, NULL, 'D. João VI', 'João Maria José Francisco Xavier de Paula Luís António Domingos Rafael de Bragança', NULL, '13/04/1767', NULL, '10/03/1826', 'https://pt.wikipedia.org/wiki/João_VI_de_Portugal', now(), now()),
(479, NULL, NULL, NULL, 'Fausto Netto', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(480, NULL, NULL, NULL, 'Jairo Régis', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(481, NULL, NULL, NULL, 'Dario Vellozo', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(482, NULL, NULL, NULL, 'Orlando Duarte', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(483, NULL, NULL, NULL, 'Ricardo Franco', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(484, NULL, NULL, NULL, 'Thomaz Koch', NULL, NULL, '11/05/1945', NULL, NULL, 'https://en.wikipedia.org/wiki/Thomaz_Koch', now(), now()),
(485, NULL, NULL, NULL, 'Alvaro-Alberto', 'Álvaro Alberto de Mota e Silva', NULL, '22/04/1889', NULL, '31/01/1976', 'https://pt.wikipedia.org/wiki/Álvaro_Alberto_da_Mota_e_Silva', now(), now()),
(486, NULL, NULL, NULL, 'F. Laboriau', 'Ferdinando Laboriau', NULL, NULL, NULL, NULL, NULL, now(), now()),
(487, NULL, NULL, NULL, 'Alfredo Lisboa', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(488, NULL, NULL, NULL, 'A. Escobar', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(489, NULL, NULL, NULL, 'Paulo Vizioli', NULL, NULL, '1934', NULL, '1999', NULL, now(), now()),
(490, NULL, NULL, NULL, 'Narciso James', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(491, NULL, NULL, NULL, 'Jê Fernandes', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(492, NULL, NULL, NULL, 'Marcos Nunes', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(493, NULL, 'Alcool Motor', NULL, 'Autoria Incerta (pseudônimo Alcool-Motor)', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(494, NULL, 'Helio Negro', NULL, 'incerto (pseudônimo Helio Negro)', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(495, NULL, NULL, NULL, 'Paulo Arbex', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(496, NULL, NULL, NULL, 'J. A. Susano', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(497, NULL, NULL, NULL, 'Edson Leite', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(498, NULL, NULL, NULL, 'Josè Clemente Pereira', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(499, NULL, NULL, NULL, 'João José Lopes Mendes Ribeiro', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(500, NULL, NULL, NULL, 'Domingos Paz', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(501, NULL, NULL, NULL, 'Maria Eugênia Boaventura', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(502, NULL, NULL, NULL, 'Maria Eugênia Boaventura', 'Maria Eugênia da Gama Alves Boaventura Dias', NULL, NULL, NULL, NULL, NULL, now(), now()),
(503, NULL, '', NULL, 'J.C.', '', NULL, NULL, NULL, NULL, '', now(), now()),
(504, NULL, NULL, NULL, 'A. R.', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(505, NULL, NULL, NULL, 'G.M.', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(506, NULL, NULL, NULL, 'Henri Mugnier', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(507, NULL, NULL, NULL, 'Antônio Carlos Couto de Barros', NULL, NULL, '19/09/1896', NULL, '16/05/1966', 'Dados biográficos em:https://pt.wikipedia.org/wiki/Antônio_Carlos_Couto_de_Barros', now(), now()),
(508, NULL, NULL, NULL, 'Olival', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(509, NULL, NULL, NULL, 'Geraldo Bretas', 'José Geraldo Bretas', NULL, '17/05/1914', NULL, '06/01/1981', 'https://pt.wikipedia.org/wiki/Geraldo_Bretas', now(), now()),
(510, NULL, NULL, NULL, 'Pereira Simões', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(511, NULL, NULL, NULL, 'F. H. Pereira Lima', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(512, NULL, 'Pojucan', NULL, 'Pojucan', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(513, NULL, NULL, NULL, 'Fernando Solera', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(514, NULL, NULL, NULL, 'F. A. Patroni M. M. P. ', 'Felipe Alberto Patroni Martins Maciel Parente', NULL, '1798', NULL, '1866', 'https://pt.wikipedia.org/wiki/Felipe_Alberto_Patroni_Martins_Maciel_Parente', now(), now()),
(515, NULL, NULL, NULL, 'J. F. Sigaud', 'José Francisco Xavier Sigaud', NULL, '1796', NULL, NULL, NULL, now(), now()),
(516, NULL, 'Amigo do Brazil', NULL, 'Desconhecido', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(517, NULL, NULL, NULL, 'Raphael Bluteau', NULL, '1638-12-04', '04/12/1638', '1734-02-14', '14/02/1734', 'https://pt.wikipedia.org/wiki/Rafael_Bluteau', now(), now()),
(518, NULL, NULL, NULL, 'Cosme III', 'Cosimo III de Medici', '1642-08-14', '14/08/1642', '1723-10-31', '31/10/1723', 'https://pt.wikipedia.org/wiki/Cosme_III_de_Médici', now(), now()),
(519, NULL, NULL, NULL, 'Troyllo de Vasconcellos da Cunha', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(520, NULL, NULL, NULL, 'Conde de Ericeyra', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(521, NULL, NULL, NULL, 'D. Francisco de Sousa', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(522, NULL, NULL, NULL, 'Carneiro', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(523, NULL, NULL, NULL, 'Monìs', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(524, NULL, NULL, NULL, 'Hasse', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(525, NULL, NULL, NULL, 'Monteyro', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(526, NULL, NULL, NULL, 'Ribeyro Rocha', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(527, NULL, NULL, NULL, 'Fr. Encarnaçaõ', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(528, NULL, NULL, NULL, 'Fr. Francisco da Natividade', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(529, NULL, NULL, NULL, 'Monteiro', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(530, NULL, NULL, NULL, 'Ribeiro', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(531, NULL, NULL, NULL, 'Rocha', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(532, NULL, NULL, NULL, 'Rebello', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(533, NULL, NULL, NULL, 'Lacerda', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(534, NULL, NULL, NULL, 'Costa', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(535, NULL, NULL, NULL, 'Carneyro', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(536, NULL, NULL, NULL, 'Gastão', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(537, NULL, NULL, NULL, 'Andrade', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(538, NULL, NULL, NULL, 'Botelho', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(539, NULL, NULL, NULL, 'D. Gaspar da Incarnaçaõ', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(540, NULL, NULL, NULL, 'Esparramante', NULL, NULL, NULL, NULL, NULL, NULL, now(), now()),
(541, NULL, NULL, NULL, 'Pelé', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());



/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
