


INSERT INTO cidades (id, nome, created_at, updated_at) VALUES
(3, 'São Paulo', now(), now()),
(4, 'Argentina', now(), now()),
(5, 'ghgh', now(), now()),
(6, 'cade', now(), now()),
(7, 'Cidade Nova', now(), now()),
(8, 'Nova Cidade', now(), now()),
(9, 'Taubaté', now(), now()),
(10, 'cac', now(), now()),
(11, 'Rio de Janeiro', now(), now()),
(12, 'Rottenbugh', now(), now()),
(13, 'Local', now(), now()),
(14, 'Lisboa', now(), now()),
(15, 'ddf', now(), now()),
(16, 'dcgdfgg', now(), now()),
(17, 'Localpublicacaoteste2', now(), now()),
(18, 'localteste5', now(), now()),
(19, 'Teste', now(), now()),
(20, 'local1', now(), now()),
(21, 'local2', now(), now()),
(22, 'Londres', now(), now()),
(23, 'Porto', now(), now()),
(24, 'Santos', now(), now()),
(25, 'Coimbra', now(), now()),
(26, 'Capital Federal', now(), now()),
(27, 's/l', now(), now()),
(28, 'Maceió', now(), now()),
(29, 'São José dos Campos (SP)', now(), now()),
(30, 'Desterro (SC)', now(), now()),
(31, 'Belo Horizonte (MG)', now(), now()),
(32, 'Bahia', now(), now()),
(33, 'Maranhão', now(), now()),
(35, 'Covilha', now(), now()),
(36, 'Pará', now(), now()),
(37, 'Formiga (MG)', now(), now()),
(38, 'Belo Horizonte', now(), now()),
(39, 'Sabará (MG)', now(), now()),
(40, 'Ouro Preto', now(), now()),
(41, 'Curitiba (PR)', now(), now()),
(42, 'Piracicaba (SP)', now(), now()),
(43, 'Aracaju (SE)', now(), now()),
(44, 'Curityba', now(), now()),
(45, 'São João dEl Rei (MG)', now(), now()),
(46, 'Crato (CE)', now(), now()),
(47, 'Ouro Preto (MG)', now(), now()),
(48, 'Fortaleza', now(), now()),
(49, 'Montes Claros (MG)', now(), now()),
(50, 'Holanda', now(), now());

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
