
INSERT INTO editoras (id, cidade_id, nome, created_at, updated_at) VALUES
(185, NULL, 'nomedeeditora', now(), now()),
(186, NULL, 'nomedeeditora', now(), now()),
(187, NULL, 'Nova Editoração', now(), now()),
(188, NULL, 'nomedeeditora', now(), now()),
(189, NULL, 'nomedeeditora', now(), now()),
(190, NULL, 'nomedeeditora', now(), now()),
(192, 3, 'EDUSP', now(), now()),
(193, NULL, 'nomedeeditora', now(), now()),
(194, NULL, 'nomedeeditora', now(), now()),
(195, NULL, 'nomedeeditora', now(), now()),
(196, 4, 'Imago', now(), now()),
(197, 5, 'ghgh', now(), now()),
(198, 6, 'cade', now(), now()),
(199, 3, 'Mamata', now(), now()),
(200, 9, 'Minhocas', now(), now()),
(201, 10, 'aca', now(), now()),
(202, 3, 'Gritos', now(), now()),
(203, 11, 'Parsival', now(), now()),
(204, 12, 'Elsevier', now(), now()),
(205, 13, 'Editora', now(), now()),
(206, 3, 'Globo', now(), now()),
(207, 14, 'Officina Ioannis Aluari typographi regii', now(), now()),
(208, 15, 'fdfd', now(), now()),
(209, 11, 's. ed.', now(), now()),
(210, 16, 'dfgdfg', now(), now()),
(211, 17, 'editorateste2', now(), now()),
(212, 18, 'editorateste5', now(), now()),
(213, 11, 's.ed.', now(), now()),
(214, 19, 'Testeeditora', now(), now()),
(215, 20, 'editora1', now(), now()),
(216, 21, 'editora2', now(), now()),
(217, 14, 'Officina Ioannis Aluari', now(), now()),
(218, 3, 'Pampas', now(), now()),
(219, 3, 'Impressão Regia', now(), now()),
(220, 3, 'Três', now(), now()),
(221, 11, 'Typographia Brasiliense', now(), now()),
(222, 22, 'Officina do Correio Braziliense', now(), now()),
(223, 11, 'Federação Espírita Brasileira', now(), now()),
(224, 3, 'Edusp', now(), now()),
(225, 3, 'Imprensa Nacional do Estado', now(), now()),
(226, 23, 'Typ. Gandra', now(), now()),
(227, 11, 'Impressão Regia', now(), now()),
(228, 14, 'Antonio Gonçaluez', now(), now()),
(229, 14, 'per Antonio Gonçalues', now(), now()),
(230, 14, 'Na nova Officina de João Rodrigues Neves', now(), now()),
(231, 24, 'Typographia Commercial', now(), now()),
(232, 14, 'Officina de Valentim da Costa Deslandes', now(), now()),
(233, 14, 'Biblioteca Nacional', now(), now()),
(234, 25, 'Officina de Manoel Dias', now(), now()),
(235, 3, 'Caras', now(), now()),
(236, 3, 'Abril', now(), now()),
(237, 26, 's/ed', now(), now()),
(238, 3, 'Numero Programma', now(), now()),
(239, 3, 'PAC', now(), now()),
(240, 27, 'Typographia de Costa Silveira', now(), now()),
(241, 28, 'Propriedade de Benedicto Vianna de Cerqueira', now(), now()),
(242, 29, 'Redator - Julio Silva', now(), now()),
(243, 11, 'Propriedade de Alberto Jacobina ', now(), now()),
(244, 30, 'Redacção de José Raposo', now(), now()),
(245, 11, 'Felix Ferreira, editor-proprietario', now(), now()),
(246, 28, 'Typ. de T. de Menezes', now(), now()),
(247, 3, 'Zulu', now(), now()),
(248, 11, 'Redactores Thomas da Porciuncula, Alberto de Menezes, e R. Teixeira Mendes', now(), now()),
(249, 31, 'Direção Cyro Siqueira, Guy de Almeida, Jacques do Prado Brandão, José Roberto D, Novaes', now(), now()),
(250, 3, 'Proprietários: dois bohemios', now(), now()),
(251, 3, 'Editor: Alvaro Duarte', now(), now()),
(252, 32, 'Typographia de Carlos Poggetti', now(), now()),
(253, 33, 'Associação Litteraria Maranhense', now(), now()),
(254, 3, 's/ed.', now(), now()),
(255, 3, 'Typographia do Farol Paulistano', now(), now()),
(256, 3, 'Imprensa de ROA EC', now(), now()),
(266, 36, 'Imprensa Liberal de Daniel Garção de Mello, e Companhia ', now(), now()),
(267, 37, 'Redator-chefe:- Dr. Aluizio de Barros Secretario:- João Ribeiro da Silva', now(), now()),
(268, 11, 's/ed.', now(), now()),
(269, 38, 'Direção Cyro Siqueira, Guy de Almeida, Jacques do Prado Brandão, José Roberto D. Novaes, ', now(), now()),
(270, 33, 'Typographia da "Pacotilha"', now(), now()),
(271, 3, 'Casa Editora Vecchi', now(), now()),
(272, 39, 'Typographia da Sociedade Pacificadora', now(), now()),
(273, 11, 's/ed', now(), now()),
(274, 36, 'Typ. de Mendonça e Baena', now(), now()),
(275, 11, 'Redator chefe: Pacheco de Andrade', now(), now()),
(276, 40, 'Officina Patricia de Barbosa, e Ca.', now(), now()),
(277, 36, 'Imprensa Liberal de Daniel Garção de Mello e Companhia', now(), now()),
(278, 11, 'Academia Brasileira de Sciencias', now(), now()),
(279, 22, 'Impresso por W. Lewis', now(), now()),
(280, 14, 's/ed.', now(), now()),
(281, 41, 'Diretor: Dario Vellozo', now(), now()),
(282, 42, 'Editor: Joaquim E. de Almeida Proença', now(), now()),
(283, 11, 'Typ. de M. de S. Rego', now(), now()),
(284, 11, 'Empresa Nacional do Diario', now(), now()),
(285, 11, 'Officina Typografica de J. Schmidt', now(), now()),
(286, 11, 'Editor: Joaquim E. de Almeida Proença', now(), now()),
(287, 3, 'Director responsavel: Antonio Gonçalves da Silva Batuira', now(), now()),
(288, 43, 'Typ. da Crença', now(), now()),
(289, 38, 'Belo Horizonte / Direção Cyro Siqueira, Guy de Almeida, Jacques do Prado Brandão, José Roberto D. Novaes ', now(), now()),
(290, 38, 'Direção Cyro Siqueira, Guy de Almeida, Jacques do Prado Brandão, José Roberto D. Novaes,.', now(), now()),
(291, 11, 'Typ. F. Borgonovo', now(), now()),
(292, 3, 'Dir. Resp. Geraldo Bretas', now(), now()),
(293, 11, 'Typ. Fluminense', now(), now()),
(294, 11, 'Typ. do Paiz', now(), now()),
(295, 3, 'Dir. resp. Geraldo Bretas', now(), now()),
(296, 44, 'Tip. Curitybana', now(), now()),
(297, 11, 'Na Officina de Silva Porto, e C.ª', now(), now()),
(298, 11, 'Typog. de Moreira, e Garcez', now(), now()),
(299, 14, 's/ed', now(), now()),
(302, 45, 'Typ. de J. Maximiano Baptista ', now(), now()),
(303, 11, 'Director: Elysio de Carvalho, Redactor-chefe: Renato Almeida, Gerente: Carlos Rubens', now(), now()),
(304, 3, 'Piratininga', now(), now()),
(305, 46, 'Diretor: J. de Figueiredo Filho; Redator secretario: José Newton Alves de Sousa; Censor Eclesiastico: Padre A. Feitosa; Gerente: João Alves Rocha', now(), now()),
(306, 47, 'Officina Patricia de Barboza E C.', now(), now()),
(307, 11, 'Redactores principaes: Teixeira de Sousa e Miguel Lemos; Typ. Cosmopolita', now(), now()),
(308, 11, 'Typographia do Diario do Rio de Janeiro', now(), now()),
(309, 11, 'Officinas Graphicas dO Malho', now(), now()),
(310, 40, 'Typographia do Universal', now(), now()),
(311, 11, 'Diretor: Anselmo Domingos', now(), now()),
(312, 40, 'Typografia do Universal', now(), now()),
(313, 11, 'Typographia de Jose Andres Garcia Ximenez', now(), now()),
(314, 11, 'Typographia de Jose Andres Garcia Ximenes', now(), now()),
(315, 3, 's/ed', now(), now()),
(316, 48, 's/ed.', now(), now()),
(317, 11, 'Diretor: Anselmo Rodrigues', now(), now()),
(318, 11, 'Typographia commercial', now(), now()),
(319, 11, 'Typ. de D. L. dos Santos', now(), now()),
(320, 11, 'Dir. Anselmo Domingos', now(), now()),
(321, 11, 'Diretor Anselmo Domingos', now(), now()),
(322, 11, 'Secretario Walfrido Ribeiro - Director Domingos Olympio - Gerente J. Gonzaga', now(), now()),
(323, 36, 'Imprensa Liberal de DanielGarção de Mello, e companhia', now(), now()),
(324, 36, 'Imprensa Liberal de Daniel Garção de Mello, e companhia', now(), now()),
(325, 3, 'Oficinas Graficas de Eugenio Cupolo', now(), now()),
(326, 11, 'Typographia de P. Plancher-Seignot', now(), now()),
(327, 3, 'Diretores responsaveis Geraldo Bretas e Luiz Vedrosi', now(), now()),
(328, 3, 'Diretor Proprietario: Geraldo Bretas - Secretario: Solange Bibas', now(), now()),
(329, 22, 'Impresso por W. Lewis, Paternoster Row', now(), now()),
(330, 22, 'Impresso por G. Greenlaw', now(), now()),
(331, 25, 'Collegio das Artes da Companhia de JESU', now(), now()),
(332, 25, 'Na Officina de Silva Porto, e C.ª', now(), now()),
(333, 25, 'No Collegio das Artes da Companhia de JESU', now(), now()),
(334, 50, 'Krasbeck', now(), now()),
(335, 3, 'SP', now(), now());

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
