

INSERT INTO hemilemas (id, hemilema, hemflex, created_at, updated_at) VALUES
(4, 'da', NULL, now(), now()),
(5, 'pe', NULL, now(), now()),
(8, 'p', NULL, now(), now()),
(9, 'pr', NULL, now(), now()),
(10, 'q', NULL, now(), now()),
(11, 'qdo', NULL, now(), now()),
(12, 'compª', NULL, now(), now()),
(30, 'estantaniamte', NULL, now(), now()),
(31, 'pa', NULL, now(), now()),
(32, 'pte', NULL, now(), now()),
(33, 'qalqr', NULL, now(), now()),
(34, 'salvamto', NULL, now(), now()),
(35, 'velocide', NULL, now(), now()),
(36, 'em', NULL, now(), now()),
(40, 'sr', NULL, now(), now()),
(42, 'ro', 'rio', now(), now()),
(43, 'mta', 'muita', now(), now()),
(44, 'mtas', 'muitas', now(), now()),
(45, 'mto', 'muito', now(), now()),
(46, 'mtos', 'muitos', now(), now()),
(47, 'qr', 'quer', now(), now()),
(48, 'sr', 'senhor', now(), now()),
(49, 'snra', 'senhora', now(), now()),
(50, 'm', NULL, now(), now()),
(51, 'dr', 'doutor', now(), now()),
(52, 'mme', 'fêmea', now(), now()),
(53, 'srs', 'senhores', now(), now()),
(54, 'sr', 'sr', now(), now()),
(55, 'etc', 'etc', now(), now()),
(56, 'v', 'v.', now(), now()),
(57, 'srs', 'srs', now(), now()),
(58, 'n', 'n.', now(), now()),
(59, 'exmº', 'Exmº', now(), now()),
(60, 'S', 'S.', now(), now()),
(61, 'sr', 'sr.', now(), now()),
(62, 'pq', 'pq', now(), now()),
(63, 'bº', NULL, now(), now()),
(64, 'q', 'que', now(), now()),
(65, 'exmº', 'Exmo.', now(), now()),
(66, 'infte', 'Infte.', now(), now()),
(67, 'mag', 'Maj.', now(), now()),
(68, 'rmº', 'Rmo.', now(), now()),
(69, 'movimº', 'movimento', now(), now()),
(70, 'ex', 'Excelentíssimo ', now(), now()),
(71, 'exm', 'Excelentíssimo', now(), now()),
(72, 'u', 'Unidade', now(), now()),
(74, 'n', 'Nossa', now(), now()),
(75, 'srs', 'Senhores', now(), now()),
(76, 'sr', 'Senhor', now(), now()),
(77, 'r', 'Raymundo ', now(), now());