

INSERT INTO ultralemas (id, remota, ultralema, lingua, comentario, assinatura, ultra_remoto, created_at, updated_at) VALUES
(119, NULL, 'AP-', 'latim', NULL, 'MEV', CAST(0 AS BOOLEAN), now(), now()),
(120, NULL, '-CUL-', 'latim', NULL, 'MEV', CAST(0 AS BOOLEAN), now(), now()),
(121, NULL, '-ON-', 'latim', NULL, 'MEV', CAST(0 AS BOOLEAN), now(), now()),
(122, 123, 'SOL-', 'latim', 'A palavra latina <i>sōl, -is</i>, masculina, permaneceu nas línguas românicas:\r\n\r\nportuguês <i>sol</i>, galego <i>sol</i>, espanhol <i>sol</i>; catalão <i>sol</i>\r\nantigo provençal <i>sol</i>\r\nitaliano <i>sole</i>\r\nlogudorês <i>sole</i>\r\ndalmático <i>saul</i>\r\nromeno <i>soare</i>.\r\n\r\nDe étimo latino também se supõe o galês <i>sul</i>.\r\n\r\nDerivações:\r\n\r\n(1) latim vulgar <i> solicŭlum</i>:\r\n\r\ncatalão <i>solell</i>;\r\nprovençal <i> solelh</i>; francês <i>soleil</i>;\r\nromanche grisão sulegl (sobresselvano <i>sulegl</i>, subselvano <i>sulegl</i>, sobremirano <i>suglegl</i>, valáder <i>sulai</i>, puter <i>sulagl</i>); gardenês <i>surëdl</i>; friulano <i>soreli</i>;\r\ncomelicano <i>soroio</i>.\r\n\r\nBibliografia: BERNARDI <i>et al.</i> (1994 <i>s. v. sulegl</i>); MEYER-LÜBKE (1992<sup>6</sup> <i>s. v. sōl, sōle</i>).', 'MEV', CAST(0 AS BOOLEAN), now(), now()),
(123, NULL, '*SÉH<sub>a</sub>UL-', 'indoeuropeu', 'Cognatos:\r\n\r\nlatim <i>sol</i>; \r\ngalês <i>haul</i>;\r\ngrego ἡέλιος;\r\ngermânico *<i>sunnō</i> (gótico <i>sunno</i> ~ <i>sauil</i>, antigo alto-alemão <i>sunna</i>, antigo saxão <i>sunna</i>, antigo nórdico <i>sunna</i> ~ <i>sól</i>, médio alto-alemão <i>sunne</i>, anglo-saxão <i>sunne</i> ~ <i>sygil</i>, antigo frâncico <i>sunne</i> ~ <i>senne</i> ~ <i>sinne</i>, alemão <i>Sonne</i>), holandês <i>zon</i>, inglês <i>sun</i>;\r\neslavo eclesiástico <i>slŭnĭce</i>;\r\nlituano <i>saulė</i>;\r\nsânscrito <i>svàr</i> ~ <i>súvar</i> ~ <i>sūrya-</i>, avéstico <i>x<sup>v</sup>əṇḡ</i>.\r\n\r\nBibliografia: KLUGE 1989<sup>22</sup> <i>s. v.</i>; MALLORY & ADAMS 2006:128.', 'MEV', CAST(1 AS BOOLEAN), now(), now()),
(126, NULL, 'cal-', 'Latim', NULL, 'MEV', CAST(0 AS BOOLEAN), now(), now()),
(127, NULL, 'brasil-', 'português', NULL, 'MEV', CAST(0 AS BOOLEAN), now(), now());
